### ISSUE TITLE
将两张大小一样的TreeMap合并到一个Grid里面，结果两个TreeMap在Grid里重叠在一起了

### ISSUE THREAD

**Issue by featherain80** [pyecharts/pyecharts-gallery#62]
vGrid = Grid(init_opts=opts.InitOpts(width='1100px',height= '400px',theme=ThemeType.SHINE))
vGrid.add(treeMap1, grid_opts=opts.GridOpts(pos_right='53%'))
vGrid.add(treeMap2, grid_opts=opts.GridOpts(pos_left='53%'))

![image](https://user-images.githubusercontent.com/84707327/128482852-6a444c5e-1c06-4c34-9c5f-468bf5884816.png)

**Comment by xiaowenfan-07** [comment]
谢谢



发自我的iPad


------------------ 原始邮件 ------------------
发件人: featherain80 ***@***.***&gt;
发送时间: 2021年8月6日 16:39
收件人: pyecharts/pyecharts-gallery ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[pyecharts/pyecharts-gallery] 将两张大小一样的TreeMap合并到一个Grid里面，结果两个TreeMap在Grid里重叠在一起了 (#62)





 
vGrid = Grid(init_opts=opts.InitOpts(width='1100px',height= '400px',theme=ThemeType.SHINE))
 vGrid.add(treeMap1, grid_opts=opts.GridOpts(pos_top = '1%',pos_left='0%',pos_right='53%'))
 vGrid.add(treeMap2, grid_opts=opts.GridOpts(pos_top = '1%',pos_left='53%'))
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shartoo** [comment]
这个代码不行吧？始终只能显示一个 TreeMap，另外一个会被覆盖
